language: node_js
node_js:
  - "node"

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
notifications:
  email: false
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
  - npm run build
before_script:
  - npm start -- --silent &
script:
  - $(npm bin)/cypress run
